# Generated by Django 5.2.8 on 2025-11-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
