# Generated by Django 5.2.8 on 2025-12-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='creative_avatars/'),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='core.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sub_category')},
            },
        ),
    ]
